### ISSUE TITLE
Camera matrices alignments

### ISSUE THREAD

**Issue by yongsiang-fb** [isl-org/TanksAndTemples#36]
Hi,

Thanks for sharing the dataset. I have a few questions:

1. In the image sets provided, the image starts with `000001.jpg` but the Camera Poses start with index 0. How do they correspond to each other?
2. I tried rendering the mesh with the camera poses and the suggested principal point offset & focal length, but the result is not aligned with the image sets (i.e., 000001.jpg). Is this expected?

Thanks a lot!

**Comment by arknapit** [comment]
1. First camera pose corresponds to the first image (pose 0 = 000001.jpg)
2. You should get descent looking overlaps in the rendering for most of the camera poses. A little offset sometimes is expected, since they are just COLMAP SfM results, not to be mistaken with actual GT. If you are off by a lot, you might want to check the aligning transformation and camera pose format.

**Comment by yongsiang-fb** [comment]
Ok. Thanks!

**Comment by elliestath** [comment]
Hey, what if I cannot recover all camera poses with my SfM system?
Can I still upload ad get scores?
In the advanced set I have some problems, not all poses are reconstructed in some datasets.
Can I create the .log file anyway? Thanks!
